# Site settings
title: Haley-Wong
SEOTitle: Haley-Wong Blog
header-img: img/bg/home.webp
email: wonghaley666@gmail.com
description: "资深iOS工程师, 应用架构"
keyword: "Haley-Wong, iOS技术博客,应用架构"
# url: ""              # your host, for absolute URL
# baseurl: ""          # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
github_username:    Haley-Wong
#zhihu_username:     Haley-Wong
# weibo_username:     Haley-Wong
#twitter_username:   
#facebook_username:  
linkedin_username:  哈雷



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: Haley-Wong



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]



# Google Analytics
#ga_track_id: 'UA-117584603-1'            # Format: UA-xxxxxx-xx



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "厚积薄发."
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Pay QRcode
#sidebar-wechat-pay: /img/wechat.jpg
#sidebar-alipay-pay: /img/alipay.jpg



# Pay Tags
pay-tags: false
pay-tags-wechat: false
pay-tags-alipay: false



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "phantomVK",
        href: "https://phantomvk.github.io/"
    }
]



# compress
compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]
